name: Publish package to GitHub Packages
on:
  release:
    types: [created]
jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'

      - name: Setup unique version
        run:  mvn --batch-mode versions:set -DnewVersion=$(date +%s) -DgenerateBackupPoms=false

      - name: Compile and prepare release
        run: mvn --batch-mode -P attach-artifacts clean install -P local-deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Deploy release
        run: mvn deploy -Dgpg.skip=true -DskipTests=true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
